### ISSUE TITLE
URGENT: Adding talks is broken.

### ISSUE THREAD

**Issue by repejota** [tlksio/front#163]
I was trying to add this talk:

https://www.youtube.com/watch?v=Qi0AhK7PMCI

But is broken showing this stacktrace on production:

```
Error: Failed to lookup view "undefined" in views directory "/opt/tlks.io/front/src/views"
   at EventEmitter.app.render (/opt/tlks.io/front/node_modules/express/lib/application.js:519:17)
   at ServerResponse.res.render (/opt/tlks.io/front/node_modules/express/lib/response.js:933:7)
   at /opt/tlks.io/front/index.js:137:9
   at Layer.handle_error (/opt/tlks.io/front/node_modules/express/lib/router/layer.js:58:5)
   at trim_prefix (/opt/tlks.io/front/node_modules/express/lib/router/index.js:300:13)
   at /opt/tlks.io/front/node_modules/express/lib/router/index.js:270:7
   at Function.proto.process_params (/opt/tlks.io/front/node_modules/express/lib/router/index.js:321:12)
   at next (/opt/tlks.io/front/node_modules/express/lib/router/index.js:261:10)
   at next (/opt/tlks.io/front/node_modules/express/lib/router/route.js:100:14)
   at Layer.handle [as handle_request] (/opt/tlks.io/front/node_modules/express/lib/router/layer.js:84:5)
```

**Comment by glopezdetorre** [comment]
csurf seems to be culprit for that, we might need to add error handling here to throw a proper error status. Funny that you got an invalid csrf token value, though :/

**Comment by glopezdetorre** [comment]
Actually, looking into it it seems to break even on correct CSRF submissions with "[TypeError: Cannot call method 'split' of undefined]". getCodeAndTypeFromRequest() is broken for YouTube videos as it tries to use var code before defining it.

**Comment by glopezdetorre** [comment]
Untested code patch, please verify:

function getCodeAndTypeFromRequest(requestUrl) {
    'use strict';

    var type, code;
    var domain = url.parse(requestUrl).hostname || '';
    var path = url.parse(requestUrl).path || '';

    switch (domain) {
        case 'youtube.com':
        case 'youtu.be':
            type = "youtube";
            code = path.match(/^(\/watch\?v=)?((^[\/])+)($|\/)/i)[2] || '';
            break;
        case 'vimeo':
            type = "vimeo";
            code = path.match(/^(\d+)(\/|$)/)[1] || '';
            break;
        default:
            throw new Error("Unsupported URL");
    }

    return [code, type];
}
